# Generated by Django 4.2.3 on 2024-03-26 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('bus_number', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('dest', models.CharField(max_length=50)),
                ('source_time', models.TimeField()),
                ('dest_time', models.TimeField()),
                ('source_date', models.DateField()),
                ('dest_date', models.DateField()),
                ('seat', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_id_proof', models.ImageField(upload_to='media')),
                ('seat', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_or_resv.bus')),
            ],
        ),
    ]
