# Generated by Django 4.2.3 on 2024-03-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_or_resv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_image',
            field=models.ImageField(default=151, upload_to='media'),
            preserve_default=False,
        ),
    ]
