# Generated by Django 4.2.3 on 2024-03-27 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus_or_resv', '0003_srcdst_remove_bus_dest_remove_bus_source_bus_srcdst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='c_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_image',
            field=models.ImageField(upload_to='bus_images'),
        ),
    ]
