# Generated by Django 4.2.3 on 2024-03-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_or_resv', '0004_remove_reservation_c_name_reservation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='c_id_proof',
            field=models.ImageField(upload_to='id_images'),
        ),
    ]
